# Generated by Django 5.2 on 2025-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("table", "datetime"),
                name="uniq_table_datetime_when_approved",
            ),
        ),
    ]
