# Generated by Django 5.2 on 2025-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_reservation_uniq_table_datetime_when_approved"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_paid", False)),
                fields=("table",),
                name="uniq_active_order_per_table",
            ),
        ),
    ]
