# Generated by Django 5.2 on 2025-08-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_order_uniq_active_order_per_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="code",
            field=models.CharField(
                db_index=True, default=1, max_length=30, unique=True
            ),
            preserve_default=False,
        ),
    ]
