# Generated by Django 5.2 on 2025-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_menuitem_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("glass", "Glass"),
                            ("terrace", "Terrace"),
                            ("green", "Green Area"),
                        ],
                        max_length=20,
                    ),
                ),
                ("top", models.FloatField(default=0)),
                ("left", models.FloatField(default=0)),
                ("width", models.FloatField(default=200)),
                ("height", models.FloatField(default=100)),
            ],
        ),
    ]
